# Cấu hình cổng cho Tomcat (Mặc định là 8080)
server.port=8080

# Cấu hình Spring MVC JSP
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Cấu hình Encoding Tiếng Việt UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
